# Generated by Django 4.2.7 on 2023-12-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0003_project_name_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name_user',
            new_name='creators',
        ),
    ]
